# Generated by Django 5.0.4 on 2024-04-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
