# Generated by Django 5.0.4 on 2024-05-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_signup_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('opt', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='NotesFiles')),
                ('comments', models.TextField()),
            ],
        ),
    ]
